import 'dotenv/config';
import mongoose from 'mongoose';
import { getCourseModel } from '../models/course.model.js';

const MONGO_URI = process.env.MONGO_URI ?? 'mongodb://localhost:27017';
const DB_NAME = process.env.DB_NAME ?? 'viana_nails';

const BASE = 'https://viananails.com/wp-content/uploads';

const courses = [
  // ── PRESENCIAL ──────────────────────────────────────────────────────────────
  {
    legacyId: 863,
    slug: 'master-level-i',
    type: 'presencial',
    name: 'Máster Level I',
    shortDesc: 'El curso más completo de la academia. Domina todas las técnicas desde cero con grupos reducidos y materiales incluidos.',
    description: 'Curso enfocado para todas las personas que quieren comenzar en el maravilloso mundo de las uñas. Encontrarás todas las técnicas más utilizadas en los salones, con productos de alta calidad y siempre con grupos reducidos para un mejor aprendizaje. Incluye: Patologías y Bioseguridad, Manicura Rusa y Combinada, Extensión en Gel, Acrílico y Acrigel, Sistema Dual y Práctica en Mano Real.',
    priceFrom: 90,
    priceTo: 739,
    badge: 'Más Popular',
    image: `${BASE}/2022/11/reserva.png`,
    order: 1,
    variations: [
      { legacyId: 865,  tipo: 'Reservar', kit: 'Sin Kit', price: 90 },
      { legacyId: 864,  tipo: 'Reservar', kit: 'Con Kit', price: 239 },
      { legacyId: 2241, tipo: 'Comprar',  kit: 'Sin Kit', price: 490 },
      { legacyId: 2242, tipo: 'Comprar',  kit: 'Con Kit', price: 739 },
    ],
  },
  {
    legacyId: 877,
    slug: 'curso-manicura-rusa',
    type: 'presencial',
    name: 'Curso Manicura Rusa',
    shortDesc: 'Aprende manicura rusa, combinada y profunda. Técnica de alto nivel con práctica en mano real.',
    description: 'Curso enfocado para todas las personas que quieren comenzar en el maravilloso mundo de las uñas, con productos de alta calidad y siempre con grupos reducidos para un mejor aprendizaje. Incluye: Manicura Rusa, Combinada y Profunda, Nivelación, Esmaltado Perfecto y Práctica en Mano Real.',
    priceFrom: 39,
    priceTo: 199,
    badge: null,
    image: `${BASE}/2023/04/manos-mujeres-hermosas-manicura-negra-despues-procedimientos-spa-concepto-tratamiento-spa_186202-8900.jpg`,
    order: 2,
    variations: [
      { legacyId: 880,  tipo: 'Reservar', kit: 'Sin Kit', price: 39 },
      { legacyId: 879,  tipo: 'Reservar', kit: 'Con Kit', price: 99 },
      { legacyId: 2199, tipo: 'Comprar',  kit: 'Sin Kit', price: 139 },
      { legacyId: 2200, tipo: 'Comprar',  kit: 'Con Kit', price: 199 },
    ],
  },
  {
    legacyId: 871,
    slug: 'curso-acrilico',
    type: 'presencial',
    name: 'Curso Acrílico',
    shortDesc: 'Técnica de extensión en acrílico desde cero. Productos de alta calidad incluidos en clase.',
    description: 'Aprende la extensión en acrílico con todo el rigor técnico: patologías, bioseguridad, colocación de molde, extensión en acrílico y retirado sin dañar la lámina ungueal. Práctica en mano real con productos incluidos.',
    priceFrom: 49,
    priceTo: 199,
    badge: null,
    image: `${BASE}/2023/04/acrilico-curso.jpg`,
    order: 3,
    variations: [
      { legacyId: 2239, tipo: 'Reservar', kit: 'Sin Kit', price: 49 },
      { legacyId: 2240, tipo: 'Reservar', kit: 'Con Kit', price: 99 },
      { legacyId: 872,  tipo: 'Comprar',  kit: 'Sin Kit', price: 149 },
      { legacyId: 873,  tipo: 'Comprar',  kit: 'Con Kit', price: 199 },
    ],
  },
  {
    legacyId: 874,
    slug: 'curso-gel',
    type: 'presencial',
    name: 'Curso Gel',
    shortDesc: 'Extensión en gel profesional. Se recomienda realizar antes el Curso de Manicura.',
    description: 'Aprende la extensión en gel con técnica profesional: patologías, bioseguridad, colocación de molde, extensión en gel y retirado sin dañar la lámina ungueal. Grupos reducidos y productos incluidos.',
    priceFrom: 49,
    priceTo: 199,
    badge: null,
    image: `${BASE}/2023/04/530be28dadbbf7bfeb93163ed4fe2d81.jpg`,
    order: 4,
    variations: [
      { legacyId: 875,  tipo: 'Reservar', kit: 'Sin Kit', price: 49 },
      { legacyId: 876,  tipo: 'Reservar', kit: 'Con Kit', price: 99 },
      { legacyId: 2237, tipo: 'Comprar',  kit: 'Sin Kit', price: 149 },
      { legacyId: 2238, tipo: 'Comprar',  kit: 'Con Kit', price: 199 },
    ],
  },
  {
    legacyId: 884,
    slug: 'curso-sistema-dual',
    type: 'presencial',
    name: 'Curso Sistema Dual',
    shortDesc: 'La combinación perfecta de gel y acrílico para estructuras de larga duración. Grupos reducidos.',
    priceFrom: 49,
    priceTo: 199,
    badge: null,
    image: `${BASE}/2022/09/home-image-5.jpg`,
    order: 5,
    variations: [
      { legacyId: 2193, tipo: 'Reservar', kit: 'Sin Kit', price: 49 },
      { legacyId: 2194, tipo: 'Reservar', kit: 'Con Kit', price: 99 },
      { legacyId: 2195, tipo: 'Comprar',  kit: 'Sin Kit', price: 149 },
      { legacyId: 2196, tipo: 'Comprar',  kit: 'Con Kit', price: 199 },
    ],
  },
  {
    legacyId: 881,
    slug: 'curso-poligel-acrigel',
    type: 'presencial',
    name: 'Curso Poligel / Acrigel',
    shortDesc: 'Domina el poligel y acrigel, los materiales más innovadores del mercado de extensión de uñas.',
    priceFrom: 49,
    priceTo: 199,
    badge: null,
    image: `${BASE}/2022/09/home-image-6.jpg`,
    order: 6,
    variations: [
      { legacyId: 2202, tipo: 'Reservar', kit: 'Sin Kit', price: 49 },
      { legacyId: 2206, tipo: 'Reservar', kit: 'Con Kit', price: 99 },
      { legacyId: 2222, tipo: 'Comprar',  kit: 'Sin Kit', price: 149 },
      { legacyId: 2223, tipo: 'Comprar',  kit: 'Con Kit', price: 199 },
    ],
  },
  {
    legacyId: 2431,
    slug: 'curso-pedicura',
    type: 'presencial',
    name: 'Curso Pedicura',
    shortDesc: 'Técnica completa de pedicura profesional. Cuidado del pie, esmaltado y acabado perfecto.',
    priceFrom: 159,
    priceTo: 175,
    badge: null,
    image: `${BASE}/2022/09/home-image-7.jpg`,
    order: 7,
    variations: [
      { legacyId: 2433, kit: 'Sin Kit', price: 159 },
      { legacyId: 2432, kit: 'Con Kit', price: 175 },
    ],
  },
  {
    legacyId: 2436,
    slug: 'curso-pestanas',
    type: 'presencial',
    name: 'Curso de Pestañas',
    shortDesc: 'Extensión y aplicación de pestañas pelo a pelo. La técnica más solicitada en los salones.',
    priceFrom: 379,
    priceTo: 410,
    badge: null,
    image: `${BASE}/2023/05/20230405_135042-scaled.jpg`,
    order: 8,
    variations: [
      { legacyId: 2438, kit: 'Sin Kit', price: 379 },
      { legacyId: 2437, kit: 'Con Kit', price: 410 },
    ],
  },
  {
    legacyId: 2441,
    slug: 'curso-depilacion-hilo',
    type: 'presencial',
    name: 'Curso Depilación Hindú | Hilo',
    shortDesc: 'Aprende la técnica oriental de depilación con hilo. Rápida, precisa y sin productos químicos.',
    priceFrom: 170,
    priceTo: 170,
    badge: null,
    image: `${BASE}/2023/05/20230402_172216-scaled.jpg`,
    order: 9,
    variations: [],
  },
  // ── ONLINE ───────────────────────────────────────────────────────────────────
  {
    legacyId: 3666,
    slug: 'master-inicial',
    type: 'online',
    name: 'Master Inicial',
    shortDesc: 'Comienza tu carrera desde cero. El pack más completo de nuestra academia online.',
    priceFrom: 299,
    priceTo: 299,
    badge: null,
    image: `${BASE}/2022/11/reserva.png`,
    order: 10,
    variations: [],
  },
  {
    legacyId: 3664,
    slug: 'sistema-dual-francesa',
    type: 'online',
    name: 'Sistema Dual Francesa',
    shortDesc: 'Aprende la técnica francesa en sistema dual online. Elegante y atemporal.',
    priceFrom: 39.99,
    priceTo: 39.99,
    badge: null,
    image: `${BASE}/2022/09/home-image-5.jpg`,
    order: 11,
    variations: [],
  },
  {
    legacyId: 3663,
    slug: 'sistema-dual-online',
    type: 'online',
    name: 'Sistema Dual',
    shortDesc: 'Técnica de sistema dual online. Aprende a tu ritmo con acceso inmediato al contenido.',
    priceFrom: 49.90,
    priceTo: 49.90,
    badge: null,
    image: `${BASE}/2022/09/home-image-6.jpg`,
    order: 12,
    variations: [],
  },
  {
    legacyId: 3662,
    slug: 'sof-gel-online',
    type: 'online',
    name: 'Sof Gel',
    shortDesc: 'Domina el soft gel online. Técnica en tendencia para estructuras naturales y delicadas.',
    priceFrom: 39.90,
    priceTo: 39.90,
    badge: null,
    image: `${BASE}/2023/04/530be28dadbbf7bfeb93163ed4fe2d81.jpg`,
    order: 13,
    variations: [],
  },
  {
    legacyId: 3661,
    slug: 'agrigel-poligel-online',
    type: 'online',
    name: 'Curso Agrigel / Poligel',
    shortDesc: 'Aprende poligel y acrigel online. Los materiales más innovadores del mercado a tu ritmo.',
    priceFrom: 49.90,
    priceTo: 49.90,
    badge: null,
    image: `${BASE}/2022/09/home-image-7.jpg`,
    order: 14,
    variations: [],
  },
  {
    legacyId: 3156,
    slug: 'curso-acrilico-online',
    type: 'online',
    name: 'Curso de Acrílico Online',
    shortDesc: 'Domina las estructuras en acrílico desde casa con acceso inmediato al curso.',
    description: 'Aprende a realizar estructuras en acrílico a tu ritmo: Anatomía de la uña, Patologías, Bioseguridad, Colocación del molde, Anclas de tensión, Preparación de la lámina ungueal, Manejo del producto, Técnica del limado y Esmaltado.',
    priceFrom: 59.90,
    priceTo: 59.90,
    badge: '¡Oferta!',
    originalPrice: 69.90,
    image: `${BASE}/2023/04/81764733-manicura-hermosa-y-arte-del-clavo-clavos-naturales-y-esmalte-de-gel-.1.jpg`,
    order: 15,
    variations: [],
  },
  {
    legacyId: 3068,
    slug: 'curso-manicura-esmaltado-online',
    type: 'online',
    name: 'Curso Manicura y Esmaltado',
    shortDesc: 'Aprende manicura rusa, combinada y esmaltado profesional desde casa, a tu ritmo.',
    description: 'Curso online completo de manicura rusa, combinada y esmaltado. Contenido: Anatomía de la uña, Patologías, Herramientas, Preparación de la lámina ungueal, Manicura combinada y rusa, Retirada de producto y Esmaltado perfecto.',
    priceFrom: 49.90,
    priceTo: 49.90,
    badge: '¡Oferta!',
    originalPrice: 59.90,
    image: `${BASE}/2023/08/manos-mujeres-hermosas-manicura-negra-despues-procedimientos-spa-concepto-tratamiento-spa_186202-7779.jpg`,
    order: 16,
    variations: [],
  },
  {
    legacyId: 3036,
    slug: 'curso-pop-art-online',
    type: 'online',
    name: 'Curso Pop Art',
    shortDesc: 'Diseños pop art sobre uñas. Creatividad y técnica en un curso online único.',
    priceFrom: 29.90,
    priceTo: 29.90,
    badge: '¡Oferta!',
    originalPrice: 39.90,
    image: `${BASE}/2022/09/home-image-10.jpg`,
    order: 17,
    variations: [],
  },
  {
    legacyId: 2708,
    slug: 'disenos-salon-online',
    type: 'online',
    name: 'Diseños de Salón',
    shortDesc: 'Los diseños más solicitados en los salones. Aprende a crearlos desde casa a tu propio ritmo.',
    priceFrom: 19.90,
    priceTo: 19.90,
    badge: '¡Oferta!',
    originalPrice: 29.90,
    image: `${BASE}/2022/09/271628359_363210472277355_7097525675050574275_n.jpg`,
    order: 18,
    variations: [],
  },
  {
    legacyId: 2660,
    slug: 'arabescos-online',
    type: 'online',
    name: 'Arabescos',
    shortDesc: 'Aprende a crear diseños arabescos sobre uñas. Técnica decorativa de inspiración oriental.',
    priceFrom: 15,
    priceTo: 15,
    badge: null,
    image: `${BASE}/2022/09/272991780_5122040217859499_2177191247324658068_n.jpg`,
    order: 19,
    variations: [],
  },
  {
    legacyId: 2697,
    slug: '3d-cristal-online',
    type: 'online',
    name: '3D Cristal',
    shortDesc: 'Diseños 3D efecto cristal sobre uñas. Técnica en tendencia para acabados transparentes y brillantes.',
    priceFrom: 18,
    priceTo: 18,
    badge: null,
    image: `${BASE}/2022/09/home-image-7.jpg`,
    order: 20,
    variations: [],
  },
  {
    legacyId: 2702,
    slug: '3d-acrilico-online',
    type: 'online',
    name: '3D Acrílico',
    shortDesc: 'Aprende a crear decoraciones 3D en acrílico. Flores, lazos y figuras en relieve.',
    priceFrom: 19.90,
    priceTo: 19.90,
    badge: null,
    image: `${BASE}/2022/09/home-image-6.jpg`,
    order: 21,
    variations: [],
  },
  {
    legacyId: 2704,
    slug: '3d-plastilina-online',
    type: 'online',
    name: '3D Plastilina',
    shortDesc: 'Domina la técnica de plastilina para uñas. Crea figuras 3D suaves y coloridas con facilidad.',
    priceFrom: 19.90,
    priceTo: 19.90,
    badge: null,
    image: `${BASE}/2022/09/home-image-5.jpg`,
    order: 22,
    variations: [],
  },
];

async function seed() {
  const conn = await mongoose
    .createConnection(`${MONGO_URI}/${DB_NAME}`, { serverSelectionTimeoutMS: 5000 })
    .asPromise();

  const Course = getCourseModel(conn);

  // Upsert por slug para que el script sea idempotente
  let inserted = 0;
  let updated = 0;

  for (const data of courses) {
    const result = await Course.updateOne(
      { slug: data.slug },
      { $set: data },
      { upsert: true }
    );
    if (result.upsertedCount) inserted++;
    else updated++;
  }

  console.log(`✓ Seed completado: ${inserted} insertados, ${updated} actualizados`);
  await conn.close();
}

seed().catch((err) => {
  console.error('Error en seed:', err.message);
  process.exit(1);
});
